# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'canny.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cancel(object):
    def setupUi(self, Cancel):
        Cancel.setObjectName("Cancel")
        Cancel.resize(682, 485)
        self.Image = QtWidgets.QLabel(Cancel)
        self.Image.setGeometry(QtCore.QRect(0, 0, 681, 321))
        self.Image.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Image.setFrameShape(QtWidgets.QFrame.Box)
        self.Image.setAlignment(QtCore.Qt.AlignCenter)
        self.Image.setObjectName("Image")
        self.horizontalSlider = QtWidgets.QSlider(Cancel)
        self.horizontalSlider.setGeometry(QtCore.QRect(20, 350, 631, 21))
        self.horizontalSlider.setStyleSheet("border:2px solid blue;")
        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setMaximum(255)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(Cancel)
        self.label.setGeometry(QtCore.QRect(20, 325, 131, 21))
        self.label.setStyleSheet("background-color: rgb(0, 0, 139);\n"
"font-size:14px;\n"
"border:1px solid blue;\n"
"border-radius: 10px;\n"
"color:white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Cancel_2 = QtWidgets.QPushButton(Cancel)
        self.Cancel_2.setGeometry(QtCore.QRect(540, 442, 101, 31))
        self.Cancel_2.setStyleSheet("background-color: rgb(0, 0, 106);\n"
"color:white;\n"
"font-size: 14px;")
        self.Cancel_2.setObjectName("Cancel_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(Cancel)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(20, 410, 631, 21))
        self.horizontalSlider_2.setStyleSheet("border:2px solid blue;")
        self.horizontalSlider_2.setMinimum(0)
        self.horizontalSlider_2.setMaximum(255)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_2 = QtWidgets.QLabel(Cancel)
        self.label_2.setGeometry(QtCore.QRect(20, 380, 131, 21))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 139);\n"
"font-size:14px;\n"
"border:1px solid blue;\n"
"border-radius: 10px;\n"
"color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Cancel)
        QtCore.QMetaObject.connectSlotsByName(Cancel)

    def retranslateUi(self, Cancel):
        _translate = QtCore.QCoreApplication.translate
        Cancel.setWindowTitle(_translate("Cancel", "Form"))
        self.Image.setText(_translate("Cancel", "Image"))
        self.label.setText(_translate("Cancel", "Lower Threshold"))
        self.Cancel_2.setText(_translate("Cancel", "Cancel"))
        self.label_2.setText(_translate("Cancel", "Upper Threshold"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cancel = QtWidgets.QWidget()
    ui = Ui_Cancel()
    ui.setupUi(Cancel)
    Cancel.show()
    sys.exit(app.exec_())
