# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Guassian.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 460)
        self.image = QtWidgets.QLabel(Form)
        self.image.setGeometry(QtCore.QRect(150, 0, 481, 361))
        self.image.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size:14px;")
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 380, 611, 21))
        self.horizontalSlider.setStyleSheet("border:2px solid blue;\n"
"")
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(31)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 350, 81, 21))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 111);\n"
"color:white;\n"
"font-size:14px;\n"
"border:1px solid blue;\n"
"border-radius:10px;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Cancel = QtWidgets.QPushButton(Form)
        self.Cancel.setGeometry(QtCore.QRect(520, 410, 101, 41))
        self.Cancel.setStyleSheet("background-color: rgb(0, 0, 98);\n"
"color:white;\n"
"font-size:14px;")
        self.Cancel.setObjectName("Cancel")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 61, 21))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 111);\n"
"color:white;\n"
"font-size:14px;\n"
"border:1px solid blue;\n"
"border-radius:10px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 10, 61, 21))
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 111);\n"
"color:white;\n"
"font-size:14px;\n"
"border:1px solid blue;\n"
"border-radius:10px;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalSlider_1 = QtWidgets.QSlider(Form)
        self.verticalSlider_1.setGeometry(QtCore.QRect(90, 40, 22, 261))
        self.verticalSlider_1.setStyleSheet("border:2px solid blue;\n"
"")
        self.verticalSlider_1.setMaximum(10)
        self.verticalSlider_1.setPageStep(1)
        self.verticalSlider_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_1.setObjectName("verticalSlider_1")
        self.verticalSlider_2 = QtWidgets.QSlider(Form)
        self.verticalSlider_2.setGeometry(QtCore.QRect(20, 40, 22, 261))
        self.verticalSlider_2.setStyleSheet("border:2px solid blue;\n"
"")
        self.verticalSlider_2.setMaximum(10)
        self.verticalSlider_2.setPageStep(1)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.image.setText(_translate("Form", "Image"))
        self.label_2.setText(_translate("Form", "Kernel Size"))
        self.Cancel.setText(_translate("Form", "Cancel"))
        self.label_3.setText(_translate("Form", "Sigma_X"))
        self.label_4.setText(_translate("Form", "Sigma_Y"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
