# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'histgram.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 460)
        self.image = QtWidgets.QLabel(Form)
        self.image.setGeometry(QtCore.QRect(0, 0, 641, 321))
        self.image.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size:14px;")
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.Cancel = QtWidgets.QPushButton(Form)
        self.Cancel.setGeometry(QtCore.QRect(490, 400, 121, 51))
        self.Cancel.setStyleSheet("background-color: rgb(0, 0, 98);\n"
"color:white;\n"
"font-size:14px;")
        self.Cancel.setObjectName("Cancel")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 360, 621, 22))
        self.horizontalSlider.setStyleSheet("border:2px solid blue;")
        self.horizontalSlider.setMaximum(255)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 330, 81, 21))
        self.label.setStyleSheet("background-color: rgb(0, 0, 120);\n"
"color:white;\n"
"font-size:14px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.image.setText(_translate("Form", "Image"))
        self.Cancel.setText(_translate("Form", "Cancel"))
        self.label.setText(_translate("Form", "Threshold"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
