# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'laplace.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 460)
        self.image = QtWidgets.QLabel(Form)
        self.image.setGeometry(QtCore.QRect(0, 0, 641, 331))
        self.image.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size:14px;")
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(19, 370, 611, 22))
        self.horizontalSlider.setStyleSheet("border:2px solid blue;\n"
"")
        self.horizontalSlider.setMaximum(7)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 340, 81, 21))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 111);\n"
"color:white;\n"
"font-size:14px;\n"
"border:1px solid blue;\n"
"border-radius:10px;")
        self.label_2.setObjectName("label_2")
        self.Cancel = QtWidgets.QPushButton(Form)
        self.Cancel.setGeometry(QtCore.QRect(500, 400, 101, 41))
        self.Cancel.setStyleSheet("background-color: rgb(0, 0, 98);\n"
"color:white;\n"
"font-size:14px;")
        self.Cancel.setObjectName("Cancel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.image.setText(_translate("Form", "Image"))
        self.label_2.setText(_translate("Form", "Kernel Size"))
        self.Cancel.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
