# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otsu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 460)
        self.image = QtWidgets.QLabel(Form)
        self.image.setGeometry(QtCore.QRect(0, 0, 641, 381))
        self.image.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size:14px;")
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.Cancel = QtWidgets.QPushButton(Form)
        self.Cancel.setGeometry(QtCore.QRect(510, 400, 121, 51))
        self.Cancel.setStyleSheet("background-color: rgb(0, 0, 98);\n"
"color:white;\n"
"font-size:14px;")
        self.Cancel.setObjectName("Cancel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.image.setText(_translate("Form", "Image"))
        self.Cancel.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
