# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sobel.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(581, 436)
        self.Image = QtWidgets.QLabel(Form)
        self.Image.setGeometry(QtCore.QRect(220, 0, 361, 331))
        self.Image.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size:14px;\n"
"border:1px solid black;")
        self.Image.setFrameShape(QtWidgets.QFrame.Box)
        self.Image.setAlignment(QtCore.Qt.AlignCenter)
        self.Image.setObjectName("Image")
        self.sobelx = QtWidgets.QLabel(Form)
        self.sobelx.setGeometry(QtCore.QRect(0, 10, 211, 151))
        self.sobelx.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font-size:14px;\n"
"border: 1px solid black;")
        self.sobelx.setFrameShape(QtWidgets.QFrame.Box)
        self.sobelx.setAlignment(QtCore.Qt.AlignCenter)
        self.sobelx.setObjectName("sobelx")
        self.sobely = QtWidgets.QLabel(Form)
        self.sobely.setGeometry(QtCore.QRect(0, 180, 211, 151))
        self.sobely.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font-size:14px;\n"
"border: 1px solid black;")
        self.sobely.setFrameShape(QtWidgets.QFrame.Box)
        self.sobely.setAlignment(QtCore.Qt.AlignCenter)
        self.sobely.setObjectName("sobely")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 350, 561, 22))
        self.horizontalSlider.setStyleSheet("border :1px solid black;")
        self.horizontalSlider.setMaximum(7)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.Cancel = QtWidgets.QPushButton(Form)
        self.Cancel.setGeometry(QtCore.QRect(430, 380, 131, 41))
        self.Cancel.setMouseTracking(False)
        self.Cancel.setStyleSheet("background-color: rgb(48, 0, 145);\n"
"font-size: 14px;\n"
"color:white;\n"
"")
        self.Cancel.setObjectName("Cancel")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 160, 61, 21))
        self.label.setStyleSheet("background-color: rgb(48, 0, 145);\n"
"color:white;\n"
"font-size:12px;\n"
"border: 1px solid white;\n"
"border-radius:10px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 330, 61, 21))
        self.label_3.setStyleSheet("background-color: rgb(48, 0, 145);\n"
"color:white;\n"
"font-size:12px;\n"
"border: 1px solid white;\n"
"border-radius:10px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Image.setText(_translate("Form", "Image"))
        self.sobelx.setText(_translate("Form", "SobelX"))
        self.sobely.setText(_translate("Form", "SobelY"))
        self.Cancel.setText(_translate("Form", "Cancel"))
        self.label.setText(_translate("Form", "Sobel_X"))
        self.label_3.setText(_translate("Form", "Sobel_Y"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
