# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 20, 241, 531))
        self.groupBox_3.setStyleSheet("border-color: rgb(34, 34, 34);\n"
"background-color: rgb(221, 221, 221);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 171, 181))
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size:14px;\n"
"QPushButton {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"    border: 2px solid #2980b9;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5dade2;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #21618c;\n"
"}\n"
"\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.Perweit = QtWidgets.QPushButton(self.groupBox)
        self.Perweit.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.Perweit.setStyleSheet("background-color: rgb(23, 17, 116);\n"
"color: white;\n"
"border: 1px solid black;\n"
"font-size:14px;")
        self.Perweit.setObjectName("Perweit")
        self.sobal = QtWidgets.QPushButton(self.groupBox)
        self.sobal.setGeometry(QtCore.QRect(10, 60, 111, 31))
        self.sobal.setStyleSheet("background-color: rgb(23, 17, 116);\n"
"color: white;\n"
"border: 1px solid black;\n"
"font-size:14px;")
        self.sobal.setObjectName("sobal")
        self.canny = QtWidgets.QPushButton(self.groupBox)
        self.canny.setGeometry(QtCore.QRect(10, 100, 111, 31))
        self.canny.setStyleSheet("background-color: rgb(23, 17, 116);\n"
"color: white;\n"
"border: 1px solid black;\n"
"font-size:14px;")
        self.canny.setObjectName("canny")
        self.laplace = QtWidgets.QPushButton(self.groupBox)
        self.laplace.setGeometry(QtCore.QRect(10, 140, 111, 31))
        self.laplace.setStyleSheet("background-color: rgb(23, 17, 116);\n"
"color: white;\n"
"border: 1px solid black;\n"
"font-size:14px;")
        self.laplace.setObjectName("laplace")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 210, 171, 151))
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size:14px;")
        self.groupBox_2.setObjectName("groupBox_2")
        self.Rotation = QtWidgets.QPushButton(self.groupBox_2)
        self.Rotation.setGeometry(QtCore.QRect(10, 30, 111, 31))
        self.Rotation.setStyleSheet("background-color: rgb(23, 17, 116);\n"
"color: white;\n"
"border: 1px solid black;\n"
"font-size:14px;")
        self.Rotation.setObjectName("Rotation")
        self.Guassian = QtWidgets.QPushButton(self.groupBox_2)
        self.Guassian.setGeometry(QtCore.QRect(10, 70, 111, 31))
        self.Guassian.setStyleSheet("background-color: rgb(23, 17, 116);\n"
"color: white;\n"
"border: 1px solid black;\n"
"font-size:14px;")
        self.Guassian.setObjectName("Guassian")
        self.Flipping = QtWidgets.QPushButton(self.groupBox_2)
        self.Flipping.setGeometry(QtCore.QRect(10, 110, 111, 31))
        self.Flipping.setStyleSheet("background-color: rgb(23, 17, 116);\n"
"color: white;\n"
"border: 1px solid black;\n"
"font-size:14px;")
        self.Flipping.setObjectName("Flipping")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 370, 171, 151))
        self.groupBox_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size:14px;")
        self.groupBox_4.setObjectName("groupBox_4")
        self.Histgram = QtWidgets.QPushButton(self.groupBox_4)
        self.Histgram.setGeometry(QtCore.QRect(10, 30, 111, 31))
        self.Histgram.setStyleSheet("background-color: rgb(23, 17, 116);\n"
"color: white;\n"
"border: 1px solid black;\n"
"font-size:12px;")
        self.Histgram.setObjectName("Histgram")
        self.adaptive = QtWidgets.QPushButton(self.groupBox_4)
        self.adaptive.setGeometry(QtCore.QRect(10, 70, 111, 31))
        self.adaptive.setStyleSheet("background-color: rgb(23, 17, 116);\n"
"color: white;\n"
"border: 1px solid black;\n"
"font-size:12px;")
        self.adaptive.setObjectName("adaptive")
        self.otsu = QtWidgets.QPushButton(self.groupBox_4)
        self.otsu.setGeometry(QtCore.QRect(10, 110, 111, 31))
        self.otsu.setStyleSheet("background-color: rgb(23, 17, 116);\n"
"color: white;\n"
"border: 1px solid black;\n"
"font-size:14px;")
        self.otsu.setObjectName("otsu")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(250, 450, 551, 101))
        self.groupBox_5.setStyleSheet("border-color: rgb(34, 34, 34);\n"
"background-color: rgb(221, 221, 221);")
        self.groupBox_5.setObjectName("groupBox_5")
        self.upload = QtWidgets.QPushButton(self.groupBox_5)
        self.upload.setGeometry(QtCore.QRect(0, 20, 141, 51))
        self.upload.setStyleSheet("background-color: rgb(23, 17, 116);\n"
"color: white;\n"
"border: 1px solid black;\n"
"font-size:14px;")
        self.upload.setObjectName("upload")
        self.cancel = QtWidgets.QPushButton(self.groupBox_5)
        self.cancel.setGeometry(QtCore.QRect(160, 20, 131, 51))
        self.cancel.setStyleSheet("background-color: rgb(23, 17, 116);\n"
"color: white;\n"
"border: 1px solid black;\n"
"font-size:14px;")
        self.cancel.setObjectName("cancel")
        self.ImageLabel = QtWidgets.QLabel(self.centralwidget)
        self.ImageLabel.setGeometry(QtCore.QRect(250, 22, 551, 431))
        self.ImageLabel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font-size: 14px;")
        self.ImageLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.ImageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ImageLabel.setObjectName("ImageLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Filters"))
        self.groupBox.setTitle(_translate("MainWindow", "Edge Detection"))
        self.Perweit.setText(_translate("MainWindow", "perweit"))
        self.sobal.setText(_translate("MainWindow", "sobal"))
        self.canny.setText(_translate("MainWindow", "canny"))
        self.laplace.setText(_translate("MainWindow", "Lapelace"))
        self.groupBox_2.setTitle(_translate("MainWindow", "morphology"))
        self.Rotation.setText(_translate("MainWindow", "Rotation"))
        self.Guassian.setText(_translate("MainWindow", "Gaussian Blur"))
        self.Flipping.setText(_translate("MainWindow", "Flipping"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Segmentation"))
        self.Histgram.setText(_translate("MainWindow", "Histgram Peak Seg"))
        self.adaptive.setText(_translate("MainWindow", "Adaptive Histgram"))
        self.otsu.setText(_translate("MainWindow", "Otsu"))
        self.groupBox_5.setTitle(_translate("MainWindow", "."))
        self.upload.setText(_translate("MainWindow", "Upload Image"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.ImageLabel.setText(_translate("MainWindow", "Select Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
